version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    links:
      - fpm
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
  fpm:
    build: ./php-fpm
    ports:
      - ":9000"
    volumes:
      - type: bind
        source: ./php-fpm/php.ini
        target: /usr/local/etc/php/conf.d/99-php.ini
      - type: bind
        source: ./php-fpm/newrelic.ini
        target: /usr/local/etc/php/conf.d/newrelic.ini
      - type: bind
        source: ./php-fpm/index.php
        target: /app/index.php

